ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Estrategia de solución


[role="arc42help"]
****
.Contenido
Un resumen corto y explicación de las estrategias y decisiones fundamentales para la solución que le dan forma a la
arquitectura del sistema.
Estas incluyen:

* Decisiones tecnológicas
* Decisiones acerca de la descomposición a alto nivel de un sistema, por ejemplo, el uso de algún patrón de diseño
o de arquitectura.
* Decisiones en como alcanzar metas de calidad claves
* Decisiones organizacionales relevantes, como el seleccionar un proceso de desarrollo o delegar ciertas tareas a terceros.

.Motivación
Estas decisiones son las piedras angulares de la arquitectura. Son la base de muchas otras decisiones detalladas o reglas de implementación.

.Forma
Realice la explicación de las decisiones clave de manera breve. 

Justifique las decisiones y porque se realizaron de esa manera, basado en el planteamiento del problema,
las metas de calidad y restricciones clave.
Refiérase a los detalles en las secciones posteriores.
****

=== Decisiones Tecnológicas
* **Microsoft Azure**: es una plataforma de computación en la nube que ofrece servicios de infraestructura, plataforma y software como servicio, para poder administrar servicios en línea.
* **MongoDB**: es un sistema de bases de datos NoSQL, es decir, una base de datos orientada a documentos. Este almacena datos con formato similar JSON, que no tienen que cumplir con una estructura predefinida.
* **JavaScript**: es un lenguaje de programación interpretado, dialecto del estándar ECMAScript. Se utiliza para crear páginas web dinámicas. 
* **React**: es una biblioteca de JavaScript para construir interfaces de usuario.
* **WikiData**: es una base de datos libre, colaborativa y multilingüe, que sirve como una base de datos secundaria y que recopila datos estructurados para dar soporte a Wikipedia, Wikimedia Commons...
* **Docker**: se utiliza para hacer el despliegue de la aplicación.
* **Bootstrap**: es un framework de código abierto para el diseño de sitios y aplicaciones web. 
 

=== Motivaciones
Hemos escogido TypeScript por su mayor parecido a Java, ya que nuestro equipo en su mayoría lo domina. En cuanto React nos basemos en que fácilmente se puede crear interfaces. El resto de tecnologías son las más óptimas y las preestablecidas, en el proyecto. Realmente estamos a la espera de los resultados de estas decisiones, ya que en su mayoría son tecnologías desconocidas para el equipo. 

* **Microsoft Azure**: la universidad nos proporciona crédito para Azure, por lo que no tendremos que pagar por el servicio y es una plataforma que ya conocemos por otras asignaturas del grado.
* **MongoDB**: el formato de los datos de MongoDB nos facilita mucho el guardado de datos en la aplicación
* **JavaScript**: aunque no lo dominamos completamente, es un lenguaje que nos era familiar y muy usado en el desarrollo web, además combinamos su uso con la biblioteca de React. 
* **React**: esta biblioteca facilita el uso de los componentes de la aplicación y, además el proyecto inicial lo usaba por lo que no se ha tenido que construir la aplicación desde cero.
* **WikiData**: su uso es un requisito obligatorio de esta aplicación pero su sistema de consultas SPARQL ha resultado muy útil a la hora de obtener las preguntas de forma dinámica y actualizada para el juego.
* **Docker**: ya configurado en el proyecto inicial por lo que pudimos crear contenedores de forma sencilla.
* **Bootstrap**: permite crear la interfaz de usuario de forma más sencilla y con diseños más agradables al cliente.


=== Decisiones sobre cómo alcanzar los objetivos clave de calidad
* **Usabilidad**: Será una aplicación sencilla, sin demasiados distractores y con los enlaces necesarios para el funcionamiento correcto del juego únicamente. Se tratará de que resulte intuitiva y fácil de usar. 
* **Seguridad**: Se configurarán los endpoints para que un usuario no autentificado pueda acceder a partes restringidas de la aplicación. Además los usuarios serán guardados con su contraseña encriptada. 
* **Disponibilidad**: El uso de Azure nos garantiza un 99,9% de disponibilidad, aunque hay que restar la dependencia que tenemos con otros servicios como Wikidata o MongoDB, de todas maneras se tratará de que la aplicación tenga la mayor disponibilidad posible.
* Utilizaremos el patrón MVC(Modelo, Vista, Controlador): Facilita la modularidad, la reutilización y el mantenimiento del código, provocando una aplicación eficiente.

=== Decisiones organizativas:
* Las tareas se reparten teniendo en cuenta las habilidades de cada uno de los integrantes del equipo y su disponibilidad.
* Los miembros del equipo mantenemos comunicación más directa a través de WhatsApp y Discord para las dudas que surjan u otras decisiones que haya que tomar en conjunto.
* Si un miembro del equipo tiene problemas con su tarea, entre los integrantes del grupo se resolverá.
* Durante el laboratorio de la asignatura, se realizarán reuniones en las que se expondrá el trabajo realizado y si alguno ha tenido algún problema con su tarea.
* Si algún miembro decide abandonar el proyecto, se repartirán sus tareas pendientes entre los miembros restantes.

[[section-views-and-perspectives]]
