ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Vista de Ejecución


[role="arc42help"]
****
.Contenido
La vista de ejecución describe el comportamiento concreto y la interacción de los bloques de construcción del sistema
en forma de escenarios en las siguientes áreas:

* Casos de uso o características importantes: ¿Cómo los ejecutan los bloques de construcción?
* Interacciones en interfases externas críticas: ¿Cómo cooperan los bloques de construcción con los usuarios y sistemas
vecinos?
* Administración y operación: Carga, inicialización, detención.
* Escenarios de error y excepción.

Observación: El criterio principal para la elección de los escenarios posibles (flujos de trabajo, secuencias) es su 
*relevancia arquitectónica*. *No* es importante describir un gran número de escenarios. Se debe documentar una selección
representativa.

.Motivación
Debe entenderse como las instancias de los bloques de construcción del sistema realizan su trabajo y se comunican en
tiempo de ejecución.
Deben capturarse principalmente los escenarios que comuniquen a las partes relacionadas que tengan problemas
para comprender los modelos estáticos en la documentación (Vista de Bloques de Construcción, Vista de Despliegue).

.Forma
Hay muchas notaciones para describir los escenarios, por ejemplo:
* Lista numerada de pasos (en lenguaje natural).
* Diagramas de flujo o de actividades
* Diagramas de secuencia
* BPMN o EPCs (Cadenas de procesos de eventos)
* Máquinas de estado
* ....
****

=== Registrar usuario
Un usuario se registra para poder jugar.

[plantuml,"Registrar usuario",png]
----
actor Usuario
participant Aplicación
database BBDD
Usuario-> Aplicación: registrarUsuario(usuario, contraseña)
Aplicación-> BBDD: validarDatos(usuario,contraseña)
BBDD--> Aplicación: confirmarValidez()
Aplicación-> BBDD: crearUsuario(usuario, contraseña)
BBDD--> Aplicación: confirmarRegistro()
Aplicación--> Usuario: mostrarMensajeExito()
----

=== Iniciar sesión
Un usuario que ya está registrado, inicia sesión con su usuario y contraseña para jugar.
[plantuml,"Iniciar sesión",png]
----
actor Usuario
participant Aplicación
database BBDD
Usuario-> Aplicación: iniciarSesion(usuario,contraseña)
Aplicación-> BBDD: validarUsuario(usuario,contraseña)
BBDD--> Aplicación: confirmarDatos()
Aplicación--> Usuario: mostrarHome()
----
=== Ver historial
Un usuario quiere ver su historial del juego.
[plantuml,"Ver historial",png]
----
actor Usuario
participant Aplicación
database BBDD
Usuario-> Aplicación: verHistorialDeJuego()
Aplicación-> BBDD: buscarHistorial(usuario)
BBDD--> Aplicación: devolverHistorial()
Aplicación--> Usuario: mostrarHistorial(historial)
----
=== Jugar y generación de preguntas
Un usuario procede a jugar, se generan las preguntas y a continuación iniciará el juego.
[plantuml,"Jugar",png]
----
actor Usuario
participant Aplicación
participant Wikidata
database BBDD
Usuario-> Aplicación: jugar()
loop Generar Preguntas
  Aplicación-> Wikidata: generarPregunta()
  Wikidata-> Aplicación: preguntasGenerada
  Usuario-> Aplicación: responder(pregunta, respuesta)
  Aplicación--> Usuario: mostrarResultado(resultado)
end
Aplicación-> Usuario: mostrarResultadosFinales()
Aplicación-> BBDD: guardarPartida()
----
