ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Vista de Ejecución


[role="arc42help"]
****
.Contenido
La vista de ejecución describe el comportamiento concreto y la interacción de los bloques de construcción del sistema
en forma de escenarios en las siguientes áreas:

* Casos de uso o características importantes: ¿Cómo los ejecutan los bloques de construcción?
* Interacciones en interfases externas críticas: ¿Cómo cooperan los bloques de construcción con los usuarios y sistemas
vecinos?
* Administración y operación: Carga, inicialización, detención.
* Escenarios de error y excepción.

Observación: El criterio principal para la elección de los escenarios posibles (flujos de trabajo, secuencias) es su 
*relevancia arquitectónica*. *No* es importante describir un gran número de escenarios. Se debe documentar una selección
representativa.

.Motivación
Debe entenderse como las instancias de los bloques de construcción del sistema realizan su trabajo y se comunican en
tiempo de ejecución.
Deben capturarse principalmente los escenarios que comuniquen a las partes relacionadas que tengan problemas
para comprender los modelos estáticos en la documentación (Vista de Bloques de Construcción, Vista de Despliegue).

.Forma
Hay muchas notaciones para describir los escenarios, por ejemplo:
* Lista numerada de pasos (en lenguaje natural).
* Diagramas de flujo o de actividades
* Diagramas de secuencia
* BPMN o EPCs (Cadenas de procesos de eventos)
* Máquinas de estado
* ....
****

=== <Escenario de ejecución 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>
