ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****

=== Registrar usuario
Un usuario se registra para poder jugar.

[plantuml,"Registrar usuario",png]
----
actor Usuario
participant Aplicación
database Pod as BBDD
Usuario-> Aplicación: registrarUsuario(usuario, contraseña)
Aplicación-> BBDD: validarDatos(usuario,contraseña)
BBDD--> Aplicación: confirmarValidez()
Aplicación-> BBDD: crearUsuario(usuario, contraseña)
BBDD--> Aplicación: confirmarRegistro()
Aplicación--> Usuario: mostrarMensajeExito()
----

=== Iniciar sesión
Un usuario que ya está registrado, inicia sesión con su usuario y contraseña para jugar.
[plantuml,"Iniciar sesión",png]
----
actor Usuario
participant Aplicación
database Pod as BBDD
Usuario-> Aplicación: iniciarSesion(usuario,contraseña)
Aplicación-> BBDD: validarUsuario(usuario,contraseña)
BBDD--> Aplicación: confirmarDatos()
Aplicación--> Usuario: mostrarJuego()
----
=== Ver historial
Un usuario quiere ver su historial del juego.
[plantuml,"Ver historial",png]
----
actor Usuario
participant Aplicación
database Pod as BBDD
Usuario-> Aplicación: verHistorialDeJuego()
Aplicación-> BBDD: buscarHistorial(usuario)
BBDD--> Aplicación: devolverHistorial()
Aplicación--> Usuario: mostrarHistorial(historial)
----
=== Jugar y generación de preguntas
Un usuario procede a jugar, se generan las preguntas y a continuación iniciará el juego.
[plantuml,"Jugar",png]
----
actor Usuario
participant Aplicación
database Pod as BBDD
participant Wikidata
Usuario-> Aplicación: jugar()
Aplicación-> Wikidata: generarPreguntas()
Wikidata--> Aplicación: preguntasGeneradas
Aplicación-> BBDD: guardarPreguntas(preguntasGeneradas)
BBDD--> Aplicación: confirmarGuardado()
loop Responder Preguntas
  Usuario-> Aplicación: responder(pregunta, respuesta)
  Aplicación-> BBDD: validarRespuesta(pregunta, respuesta)
  BBDD--> Aplicación: resultado
  Aplicación--> Usuario: mostrarResultado(resultado)
end
----
