ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]

=== Modelo de dominio
Este es el modelo inicial de nuestra aplicación, pero evolucionará con el tiempo.

----
clase Usuario{
    id: String
    nombre: String
    fecha_registro: String
}

clase Partida{
    id: String
    puntuación: int
    preguntas: Array<Pregunta>
    preguntas_acertadas: int
    preguntas_falladas: int
}

clase Pregunta{
    id: String
    texto: String
    respuestas: Array<Respuesta>
}

clase Respuesta{
    id: String
    texto: String
    correcta: boolean
}

Usuario 1 ---> * Partida
Partida 1 ---> (5..20) Pregunta
Pregunta 1---> (2..4) Respuesta

----

=== Arquitectura principal

Hemos decidido utilizar una arquitectura de microservicios, dividiendo la aplicación en módulos. Estos módulos a su vez, se estructurarán con el patrón MVC.


=== Reglas al usar una tecnología específica:

Realmente no sabemos demasiado sobre las tecnologías elegigidas, con la evolución del equipo mejoraremos esta sección.


=== Reglas de implementación

Como es un proyecto en equipo creemos que la colaboración es lo más importante, por eso hemos decidido comentar lo máximo posible nuestro propio código para que sea entendible por otras personas/compañeros de equipo.

=== Interfaz de usuario.

Queremos crear una aplicación accesible para todos los usuarios, que sea simple de entender y de jugar, que lo máximo que tengas que pensar sean las preguntas del juego.

=== Privacidad 

Los usuarios se tienen que autenticar para poder utilizar la aplicación, además sus contraseñas están encriptadas.

