ifndef::imagesdir[:imagesdir: ../images]

[[section-glossary]]
== Glossary

[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms


.Form

A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.


.Further Information

See https://docs.arc42.org/section-12/[Glossary] in the arc42 documentation.

****

[cols="e,2e" options="header"]
|===
| Término | Definición

| WikiData
| Base de conocimientos con una gran cantidad de datos. Extraeremos datos de WikiData a través de la API que nos proporciona. Construiremos las preguntas con estos datos.

| MVC
| Modelo de arquitectura de software. Las aplicaciones que siguen este modelo se dividen en 3 capas, Modelo, Vista y Controlador.

|===
